<style>
	/* This is how I personally write my CSS */
	
	div.quickShopBody{width:100%;display:flex;flex-flow:row wrap;}
	div.quickShopBody div.qsRow{width:100%;display:flex;flex-flow:row wrap;justify-content:center;align-items:center;}
	div.quickShopBody a{display:block;height:65vh;flex:1 1 auto;cursor:pointer;background-position:50% 0%;background-size:cover;background-repeat:no-repeat;transition:all ease 120ms;min-width:200px;}
	div.quickShopBody a:hover{box-shadow:inset 0 0 30px 10px white;}


	/*
		Thus its rather easy to just translate it into SASS syntax

	*/

	/* However, since Magento 1 doesn't have a built-in SASS parser, I will use pre-compiled CSS:*/

</style>
<script type="text/javascript">
	// jQuery('body').on('click','div.quickShopBody div.qsRow a',function(e){
	// 	e.preventDefault();
	// 	window.location.href=jQuery(this).attr('target');

	// 	// Instead of loading the target URL in the same tab, we can open a new one [can be alterable through a setting]
	// 	// window.open(jQuery(this).attr('target'),'_blank');
	// });
</script>
<div class='quickShopBody'>
	<div class='qsRow'>
<?php
$perRow=Mage::getStoreConfig('quickshop/settings/row_items');
$c=1;
$total=count($this->getQuickShopGallery());
foreach($this->getQuickShopGallery() as $k=>$image){
	echo '<a c="'.$c.'" href="'.$image->getLink().'" style="background-image:url(/media/'.$image->getImageName().');" target="_blank" ></a>'.(($c%$perRow)==0&&$total>$c?'</div><div class="qsRow">':'');
	$c++;
}
?>
	</div>
</div>